### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pir8radio** [oottppxx/enigma2#13]
you should just have this script run daily and let people access the xml through your web server :-)  I'm on windows and have no idea how to use this python script...   just saying...  :-)

**Comment by oottppxx** [comment]
I'm presuming you mean the vaders-mc2xml.py script.

I have no webserver nor do I intend to have one.

Folks are free to use the script in whatever way, but it was done primarily to help out someone with TVHeadend at the time - folks running it are presumed to have some technical know-how to run it and/or tweak it, as indicated in the README. What would one do with the XML output, anyway, in Windows?

I suggest you read https://docs.python.org/2.7/using/windows.html and tweak the script for your own purposes.
