### ISSUE TITLE
How to bind button?

### ISSUE THREAD

**Issue by Lee-Fixter** [oottppxx/enigma2#19]
Hi,

How do we bind a button to quickly launch Heinz?

**Comment by oottppxx** [comment]
That will depend on the system you use.

On OpenATV, Menu > Setup >Usage & GUI > Hotkey setup, then press the key you want to use as a shortcut, and select Heinz from the Plugins, then save and exit.

OpenPLi is quite similar, but I don't remember the sequence of the top of my head.

Other systems may differ, if they even support Heinz.

**Comment by Lee-Fixter** [comment]
Perfect, thanks
