### ISSUE TITLE
Bigmac is not declaring probes ok correctly

### ISSUE THREAD

**Issue by ian10951** [oottppxx/enigma2#20]
This is causing the stream to be restarted even when its not required and there isnt a drop in the network connection to the IPTV server.

It seems that the stream is restarted depending upon the settings of option 4 regardless. so if this is set to 5 the the stream will restart every 5 seconds, if its set to 1 then it restarts every second basically causing the box to lock up. It seems that no mater what is added to the RX Queue Threshold, its never taken into account, so basically its not counting probes ok and resetting the count correctly. Great effort though and a massive step forward. I just hope the resetting of the count can be fixed.

Of course if this is set to a high value such as 60 then it wont be as annoying and will only restart every 60 seconds ( required or not ) but when you do get a true network drop, you then have to wait 60 seconds for the stream to restart. I might as well pick up my remote and restart it myself than wait 60 secs lol.

**Comment by oottppxx** [comment]
Can you paste a screenshot of your BigMac setup screen, or the value for all the entries, including version?

**Comment by ian10951** [comment]
At the moment my setting are 

6.2.0.d
true
5
5
10
0
false

But Ive tried every possible combination imaginable, including your default settings and other settings that you say on the tekings forum that you are currently using. It seems to make no odds and the RX Queue Threshold setting seems to be being ignored. Ive checked the debug log and it never ever states that the count has been reset so that it begins again.

**Comment by oottppxx** [comment]
Yes, that seems very odd.

I'd recommend to use the poll interval as 1, to start with, but the RX Queue Threshold should be way higher (1024), the fact that the consecutive count isn't resetting with such a low value is very strange.

If you have terminal access to the box (telnet, ssh, openwebif), you can either do "cat /proc/net/tcp" and examine the rx_queue column, or just do "netstat -tn" and examine the Recv-Q column (the latter being easier to read) - the plugin uses the /proc/net/tcp file, so if you have a problem displaying it, maybe there's something wrong with the box/system, too (not likely).

Repeat the commands several times and see how the value changes for those columns, namely on the connection related to your stream. If you see the connection if breaking often (port values change on your side, etc...) and the receive queue doesn't maintain a value higher than whatever you put into the threshold setting, in general, that's the issue. If the value displayed is generally higher, that would indicate an issue with the plugin, but I use it myself and haven't seen such issue.

**Comment by ian10951** [comment]
Here's my debug log ( server details edited ) This is from my TvHeadend Server however its exactly the same behaviour when connecting directly to Xtreme Codes IPTV Servers in my bouquets.
[bigmac-debug.log](https://github.com/oottppxx/enigma2/files/3388875/bigmac-debug.log)

**Comment by oottppxx** [comment]
Your stream URL doesn't seem to contain m3u8, mp4, or mkv, as such it isn't being ignored by the BigMac plugin (this isn't a setting right now, but maybe I can expose it).

The log confirms that the plugin is seeing the sum of all active TCP sockets rx_queue values as 0 and you set 5.

You're using service type 5002/exteplayer3 to display the stream, which is fine, however, can you confirm if the stream is of type MPEG2TS (TS)? Because if it's an IPTV M3U8 stream, it will create very short (in time) TCP connections instead of a very long one, and that can affect the rx_queue measurements, of course (which is why we ignore m3u8 streams, as those should be able to restart themselves w/high probability, too).

If you can play the same URLs using the default 1/DVB service, then it should be an MPEG2TS stream, and you really need to check if /proc/net/tcp is really reporting zeros for rx_queue; if it is, there's nothing the plugin can do and you'll have to disable it.

Hit me up on Telegram if you need help with some interactive debugging.

**Comment by ian10951** [comment]
Yes its a ts stream. Its piped though through FFMPEG on the Server and then converted to ts as TvHeadend only understands ts IPTV streams. As I say though its behaving exactly the same when just using Xtreme Codes IPTV Servers directly from my Bouquets. I have also tried Gstreamer too rather than Exteplayer3 but that makes no difference either, its still giving unnecessary restarts. 
The proc/net/tcp is not reporting any zeros for the rx_queue as far as I can tell.

Anyway thanks for your time and help, I just thought I would report the issue as I do know others have this problem too. Your plugin is beginning to get uploaded on various forums now and this is where Ive seen that others have the problem of unnecessary restarts as well. I understand its very difficult to help like this, but at least your now aware that there maybe a problem.

**Comment by oottppxx** [comment]
Ok, thanks. What system are you using? OpenATV, OpenPLi, other? Plus the version, please.

**Comment by ian10951** [comment]
OpenATV 6.3 on a VU+ Solo4K

**Comment by oottppxx** [comment]
Ok, thank you, I run OpenATV 6.2, wouldn't expect it to be an issue but I'll try it on 6.3 sometime during the weekend to check (no VU+ Solo 4K, though, eh!)

**Comment by ian10951** [comment]
Ok that's great and Thank You for your time and patience.

**Comment by ian10951** [comment]
Ok further to this, Ive discovered that when streaming from Tvheadend, even though it is a ts stream the ERXQ is always 0.

Other Servers in my Bouquets ( not all ) give an ERXQ of at least 1125576 and with my RXQT set to 5 the plugin works perfectly ( I now see that a setting of 5 is probably too low lol )

So

Have you any idea why a TvHeadend stream gives an ERXQ of 0 ?

It is piped and transcoded to ts, but like you said in your earlier post, the ts part of the stream isnt showing and so perhaps isnt being picked up by your plugin ? I'm just guessing here. If this is the case do you know of anything that can be done to the pipe to make sure that the Recv-Q packets are not 0 ?

At the moment as things stand your plugin doesnt work with TvHeadend streams which is a blow.

**Comment by oottppxx** [comment]
I'm glad you verified that the plugin works correctly for other servers.

It's probably less to do with TvHeadend and more about the network topology and settings. If your TvHeadend server is in the LAN, as I suspect, with an extremely low RTT, then it may well be that influences the RX queue in that manner; as I said, if the value is always zero, there's nothing the plugin can do. In any case, shouldn't any stream freezing issue then be solved on the TvHeadend to IPTV server side? I understand you might like the plugin to trigger a refresh to TvHeadend, but I don't think that's possible.

I'm guessing a workaround on the plugin side, besides a manual disable, is for me to explicit the strings that would make the plugin ignore a particular service (currently m3u8, mp4, and mkv), so you could add the TvHeadend or other servers/services specific strings/hosts to it, so those services would automatically be ignored by BigMac and wouldn't attempt to restart them.

**Comment by ian10951** [comment]
Thanks.

Yes Ive already done that in my version, mainly so your plugin can restart streams such as m3u8, mp4 and mkv, even though VOD will always restart from the beginning again its still better than having to get up and pick up the remote to restart it again lol ( lazy git aren't i ) So i do think other users may want this option too and adding that setting would indeed be a good idea.

Yes your quite correct about Tvheadend. It is indeed capable of restarting the stream to the Server when piped through FFMPEG, and I do use this feature. However, the problem has always been with E2 in the fact that the connection timeout is set too low, and by the time the pipe has reconnected to the IPTV Server, E2 has disconnected from TvHeadend. We are only talking less than 2 seconds here for TvHeadend to reconnect to the IPTV Server, but its enough for E2 to consider the stream dead and disconnect from TvHeadend. Its most annoying, thats why your plugin is such a blessing.

**Comment by oottppxx** [comment]
Updated the plugin with the new setting, and removed the old total probes setting while I was at it.

Nothing more I can do, there's no magic to be had here, the plugin seems to be working as intendend, closing.

**Comment by ian10951** [comment]
Just to add before you close this for good, that your new file works.

Just for info for others also using TvHeadend. As there is no string in the TvHeadend url to add to the ignore setting, you have to add the Contabo IP instead. This is acceptable because the code allows wildcards. So anyone wishing to use this plugin on everything other than TvHeadend needs to also do this.
