### ISSUE TITLE
Latest update for Quaterpounder

### ISSUE THREAD

**Issue by ian10951** [oottppxx/enigma2#22]
Hi, can you shed any light on what values we enter into the config for the latest hack for stuck streams ?
Is it the stream type ? ie ts, thats all I could think of, but this could be anything lol

**Comment by oottppxx** [comment]
It's basically one or several, separated by commas, strings to match service strings; think 1:0:1:aaaa:bbbb:,1:0:1:cccc:dddd:, etc...

When you zap to a service that matches, it will trigger an unconditional restart after the number of milliseconds defined in the numeric parameter; hopefully of the same service, but could be another if your zapping is quite fast (I didn't put many safeguards in).
