### ISSUE TITLE
Heinz - OpenVix Issues

### ISSUE THREAD

**Issue by TurnipFarmer76** [oottppxx/enigma2#26]
Hi oottppxx;

Not submitted one of these before;  Heinz crashes my receiver freshly installed with OpenVix Latest 5.4.005 using an sf8008 i saw the same issue on a forum with a Zgemma so know it's not just box related.

[heinz-debug.log](https://github.com/oottppxx/enigma2/files/5912696/heinz-debug.log)
[Enigma2_crash_2021-02-02_16-18-03.log](https://github.com/oottppxx/enigma2/files/5912697/Enigma2_crash_2021-02-02_16-18-03.log)

I attach the Heinz Debug Log and My Enigma Log I belive I have sanitised them both

Thanks

**Comment by oottppxx** [comment]
What version of Heinz?

**Comment by TurnipFarmer76** [comment]
enigma2-plugin-extensions-heinz-6.2.2q.ipk Fresh Install this morning

**Comment by TurnipFarmer76** [comment]
Hi, 

I reinstalled twice before coming here confirmed the directory only has the normal files in it

root@sf8008:/usr/lib/enigma2/python/Plugins/Extensions/Heinz# ls
README.txt    heinz.png     plugin.pyo
__init__.pyo  keymap.xml    setup.xml

I tried the older version and that still has issues, although they look slightly different. 
[Enigma2_crash_2021-02-02_17-41-43.log](https://github.com/oottppxx/enigma2/files/5913244/Enigma2_crash_2021-02-02_17-41-43.log) - This is Version m

[Enigma2_crash_2021-02-02_17-49-37.log](https://github.com/oottppxx/enigma2/files/5913280/Enigma2_crash_2021-02-02_17-49-37.log) - This is the latest version

Thanks, I understand you're probably busy, 
I think there different errors if you can point me in the right direction I am happy to take a look-see if I can fix it and submit a request If I manage it, its been a few years since I looked at any Python.

Thanks

**Comment by stingray82** [comment]
@TurnipFarmer76  I too, reinstalled VIX for another issue this morning and noticed issues with Heinz and possibly Quaterpounder which I haven't investigated yet. 

I have had a look at yours and my error logs and after some trial, and error can confirm that I have got my box working by making two edits, to the VIX only part of the Script for information the stuff i changed was:

Line 17 change `openatv_like = True ` so it reads `openatv_like = False`

Then

Line 784 change `SingleEPG.__init__(self, session, service=service)` so it now reads `SingleEPG.__init__(self, session, service=str(service))`

I was able to play a stream and catchup in VIX and OpenATV was unchanged.

If you could confirm this works for you; I have attached a PYO file to this so you can download it and replace it in your Extensions/Heinz directory

[plugin.zip](https://github.com/oottppxx/enigma2/files/5915730/plugin.zip)

Cheers Stingray

**Comment by oottppxx** [comment]
This should be fixed in the latest push - tested w/OpenViX 5.4.009.
