### ISSUE TITLE
python on dependencies

### ISSUE THREAD

**Issue by davesayers2014** [oottppxx/enigma2#29]
https://github.com/oottppxx/enigma2/blob/360ee8ee5675ff6a11267f71a117ee4e05a861cb/plugins/quarterpounder/src/control.tmpl#L9

I don't think this is needed and causes issues on vix py3 images 

`root@vuuno4k:~# opkg install https://github.com/oottppxx/enigma2/blob/master/plugins/quarterpounder/enigma2-plugin-extensions-quarterpounder-6.2.0l.ipk?raw=true
Downloading https://github.com/oottppxx/enigma2/blob/master/plugins/quarterpounder/enigma2-plugin-extensions-quarterpounder-6.2.0l.ipk?raw=true.
 * calculate_dependencies_for: Cannot satisfy the following dependencies for enigma2-plugin-extensions-quarterpounder:
 *      python * 
 * opkg_solver_install: Cannot install package enigma2-plugin-extensions-quarterpounder.`

**Comment by defkev** [comment]
Will this is a weird dependency you can ignore it using `--force-depends`

**Comment by oottppxx** [comment]
Thanks both for the comments - I'll try and remove the dependency across the various plugins sometime this weekend, time allowing.

**Comment by oottppxx** [comment]
Please test for QuarterPounder, which I've just updated; if all is good, I'll update the leftovers at some leisure.

**Comment by davesayers2014** [comment]
> Please test for QuarterPounder, which I've just updated; if all is good, I'll update the leftovers at some leisure.

That seems to be working on my vu Uno4k using vix py3 image. Thanks
