### ISSUE TITLE
Please add OpenBH

### ISSUE THREAD

**Issue by Ev0-BH** [oottppxx/enigma2#32]
As title, please change line 15 in QuarterPounder to this:

if boxbranding.getImageDistro() in ('openbh', 'openvix'):

**Comment by Ev0-BH** [comment]
I think with Heinz you could probably get away with similar, and set openbh=vix

**Comment by oottppxx** [comment]
I'll take a look over the weekend, although it's simple enough I like to test; what OpenBlackHole version did you test with?

**Comment by Ev0-BH** [comment]
4.4 and 5.0 (in beta so not released yet) Ultimo4K (I have to admit I haven't fully tested Heinz myself, but confirm Quarterpounder is all good).

**Comment by Ev0-BH** [comment]
Did you get around to testing this ?

**Comment by oottppxx** [comment]
I haven't, and won't be able to until mid-February, sorry.

**Comment by Ev0-BH** [comment]
ok

**Comment by Ev0-BH** [comment]
Just a gentle reminder for you to add OpenBh

**Comment by oottppxx** [comment]
Fixed in 6.2.0r, give it a whirl, and reopen if there's something broken.
