### ISSUE TITLE
Quarter Pounder: Gstreamer HLS support

### ISSUE THREAD

**Issue by defkev** [oottppxx/enigma2#37]
I just noticed the other day Quarter Pounder doesn't work with Gstreamer (reftype 4097) for HLS (HTTP Live Streaming) because evEOF never fires, oddly enough ExtPlayer3 (5002) does, so I assume this is a limitation of Gstreamer?

**Comment by oottppxx** [comment]
I would think so, nothing QP can do if it doesn't see the EOF events.
